version: '3.8'

services:
  backend:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db:27017/flutter_db

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - flutter_db:/data/db 

volumes:
  flutter_db:
